"""
financial_state.py — builds one canonical FinancialState per (user, request).

This is the "Financial State Builder" box in the architecture diagram. It
turns raw rows (events, messages, images, payment options, profile) into a
single normalized, deduplicated, evidence-resolved picture that the
deterministic forecast/optimizer/validator layers consume. No LLM calls
happen here beyond the injected evidence resolvers, and those resolvers only
extract facts — they never compute affordability.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, timedelta
from decimal import Decimal
from typing import Optional

from . import config
from .data_loader import Dataset
from .evidence import ImageEvidenceResolver, MessageEvidenceResolver
from .fx import ExchangeRateTable
from .models import FinancialEvent, PaymentOption, Profile, Request


def _advance(d: date, interval_days: int, monthly: bool) -> date:
    """Step a projected recurrence date forward by one period. Monthly
    cadences (~25-35 day observed gaps) step by calendar month, preserving
    the day-of-month (clamped to the last valid day), so a salary/rent date
    of the 15th stays on the 15th indefinitely instead of drifting across
    28/29/30/31-day months. Weekly/other cadences step by a fixed day count,
    which is exact for those periods."""
    if not monthly:
        return d + timedelta(days=interval_days)
    month = d.month + 1
    year = d.year + (month - 1) // 12
    month = ((month - 1) % 12) + 1
    # Clamp day to the last valid day of the target month.
    if month == 12:
        next_month_first = date(year + 1, 1, 1)
    else:
        next_month_first = date(year, month + 1, 1)
    last_day_of_month = (next_month_first - timedelta(days=1)).day
    day = min(d.day, last_day_of_month)
    return date(year, month, day)


@dataclass
class CashEvent:
    """A single dated cash-flow line used by the forecast engine, already
    converted to the user's home currency."""
    event_id: str
    category: str
    direction: str  # credit | debit
    amount: Decimal  # in home currency, always positive
    on_date: date
    flexibility: str
    protected: bool
    reducible: bool
    stoppable: bool
    minimum_allowed_amount: Optional[Decimal]
    is_projected: bool = False  # True if generated by recurrence projection
    note: str = ""
    description: str = ""


@dataclass
class FinancialState:
    user_id: str
    request_id: str
    request_date: date
    requested_amount: Decimal
    home_currency: str
    current_balance: Decimal
    minimum_balance: Decimal
    desired_completion_date: date
    priorities: list[str]
    payment_preferences: set[str]
    max_installment_months: Optional[int]
    forecast_horizon_end: date
    cash_events: list[CashEvent]  # all committed/projected events within horizon, chronological
    payment_options: list[PaymentOption]
    evidence_notes: list[str] = field(default_factory=list)


class FinancialStateBuilder:
    def __init__(self, dataset: Dataset, fx: ExchangeRateTable,
                 image_resolver: ImageEvidenceResolver,
                 message_resolver: MessageEvidenceResolver) -> None:
        self.ds = dataset
        self.fx = fx
        self.image_resolver = image_resolver
        self.message_resolver = message_resolver
        self._resolved_amount_cache: dict[str, Decimal] = {}

    # -- amount resolution -------------------------------------------------
    def _resolve_blank_amount(self, event: FinancialEvent) -> Optional[Decimal]:
        if event.event_id in self._resolved_amount_cache:
            return self._resolved_amount_cache[event.event_id]
        image_ref = self.ds.images_by_related_event.get(event.event_id)
        if not image_ref:
            return None
        result = self.image_resolver.resolve(image_ref)
        if result.amount is not None:
            self._resolved_amount_cache[event.event_id] = result.amount
        return result.amount

    # -- message-based amendment / cancellation signals ---------------------
    def _message_signals_for_event(self, user_id: str, event_id: str) -> list:
        sigs = []
        for m in self.ds.messages_by_user.get(user_id, []):
            if m.related_event_id == event_id:
                sigs.append(self.message_resolver.parse(m))
        return sigs

    def _employer_salary_override(self, user_id: str, home_currency: str,
                                   as_of: date) -> Optional[tuple[Decimal, str]]:
        """Look for the most recent employer message (not tied to a specific
        event row) that states a concrete new salary figure. Used only to
        corroborate/override the *amount* of upcoming salary events, never to
        invent a salary where none exists in financial_events.csv."""
        best: Optional[tuple[str, Decimal, str]] = None  # (sent_at, amount, currency)
        for m in self.ds.messages_by_user.get(user_id, []):
            if m.source_type != "employer" or m.related_event_id:
                continue
            sig = self.message_resolver.parse(m)
            if sig.intent != "amendment" or not sig.currency_amounts:
                continue
            for code, amt in sig.currency_amounts:
                if code == home_currency:
                    if best is None or m.sent_at > best[0]:
                        best = (m.sent_at, amt, code)
        if best is None:
            return None
        return best[1], best[2]

    # -- classification ------------------------------------------------------
    def _classify(self, event: FinancialEvent, profile: Profile) -> tuple[bool, bool, bool]:
        protected = event.category in profile.expense_categories_to_protect
        reducible = (
            event.category in profile.expense_categories_user_is_willing_to_reduce
            and event.flexibility in config.FLEXIBLE_REDUCIBLE
        )
        stoppable = (
            event.category in profile.expense_categories_user_is_willing_to_stop
            and event.flexibility in config.FLEXIBLE_STOPPABLE
        )
        return protected, reducible, stoppable

    # -- recurrence detection --------------------------------------------
    def _detect_recurring_categories(self, user_id: str, request_date: date) -> dict[str, dict]:
        """From *historical settled* events, detect categories/streams that
        recur on a roughly regular cadence, so the 90-day forecast reflects
        ongoing obligations and ongoing base income even when
        financial_events.csv only contains one or two explicit future rows.

        Debit (expense) categories: cadence-only detection (weekly/monthly),
        amount naturally fluctuates month to month so no amount-consistency
        filter is applied; the most recent observed amount is projected
        forward.

        Credit (income): restricted to the 'salary' category only — we never
        project bonuses, commissions, investment gains, or other variable
        credits into the future (per the "do not count until settled" rule).
        A user's salary history can contain two interleaved streams (a
        constant base salary and a variable bonus/commission on a different
        day of month); events are first clustered by amount similarity so
        only the consistently-constant stream is treated as recurring.
        """
        history = [
            e for e in self.ds.events_by_user.get(user_id, [])
            if e.status == "settled" and e.event_date <= request_date
            and e.direction == "debit"
        ]
        debit_by_cat: dict[str, list[FinancialEvent]] = {}
        for e in history:
            debit_by_cat.setdefault(e.category, []).append(e)

        recurring: dict[str, dict] = {}

        for cat, events in debit_by_cat.items():
            info = self._cadence_from_events(events, require_amount_consistency=False)
            if info:
                recurring[cat] = info

        # Salary: financial_events.csv always carries at most one
        # authoritative "next confirmed salary" row (settled, scheduled, or
        # pending) per user. Rather than requiring 3 historically-consistent
        # occurrences (which fails right after a raise, when only one
        # instance of the new amount exists), anchor on whichever known
        # salary event is most recent (by event_date, including the future
        # confirmed one) and assume it continues monthly at that same
        # amount. This matches the dataset's evident design intent: a raise
        # changes the ongoing recurring amount immediately, it does not need
        # 3 confirmations to be believed.
        salary_events = [
            e for e in self.ds.events_by_user.get(user_id, [])
            if e.category == "salary" and e.direction == "credit"
            and e.status in ("settled", "scheduled", "pending")
        ]
        if salary_events:
            anchor = max(salary_events, key=lambda e: e.event_date)
            amt = anchor.amount if anchor.amount is not None else self._resolve_blank_amount(anchor)
            if amt is not None:
                recurring["salary"] = {
                    "interval_days": 30,
                    "last_amount": amt,
                    "last_currency": anchor.currency,
                    "last_date": anchor.event_date,
                    "flexibility": anchor.flexibility,
                    "description": anchor.description,
                }
        return recurring

    @staticmethod
    def _cluster_by_amount(events: list[FinancialEvent], tolerance: Decimal) -> list[list[FinancialEvent]]:
        """Greedy 1D clustering: sort by amount, start a new cluster whenever
        consecutive amounts differ by more than `tolerance` (relative)."""
        valid = [e for e in events if e.amount is not None]
        valid.sort(key=lambda e: e.amount)
        clusters: list[list[FinancialEvent]] = []
        for e in valid:
            if clusters and e.amount > 0 and clusters[-1]:
                last_amt = clusters[-1][-1].amount
                if last_amt > 0 and abs(e.amount - last_amt) / last_amt <= tolerance:
                    clusters[-1].append(e)
                    continue
            clusters.append([e])
        return clusters

    @staticmethod
    def _cadence_from_events(events: list[FinancialEvent], require_amount_consistency: bool) -> Optional[dict]:
        events = sorted(events, key=lambda e: e.event_date)
        if len(events) < 3:
            return None
        gaps = [
            (events[i + 1].event_date - events[i].event_date).days
            for i in range(len(events) - 1)
        ]
        gaps = [g for g in gaps if g > 0]
        if not gaps:
            return None
        median_gap = sorted(gaps)[len(gaps) // 2]
        if not (5 <= median_gap <= 40):
            return None
        consistent = sum(1 for g in gaps if abs(g - median_gap) <= max(3, 0.4 * median_gap))
        if consistent < max(1, int(0.6 * len(gaps))):
            return None
        if require_amount_consistency:
            amounts = [e.amount for e in events if e.amount is not None]
            if len(amounts) < 3:
                return None
            mean = sum(amounts) / len(amounts)
            if mean == 0:
                return None
            max_dev = max(abs(a - mean) for a in amounts)
            if max_dev / mean > Decimal("0.03"):
                return None
        last = events[-1]
        if last.amount is None:
            return None
        return {
            "interval_days": median_gap,
            "last_amount": last.amount,
            "last_currency": last.currency,
            "last_date": last.event_date,
            "flexibility": last.flexibility,
            "description": last.description,
        }

    # -- main build ----------------------------------------------------------
    def build(self, request: Request) -> FinancialState:
        profile = self.ds.profiles[request.user_id]
        horizon_end = request.request_date + timedelta(days=config.FORECAST_HORIZON_DAYS)
        notes: list[str] = []

        cash_events: list[CashEvent] = []
        seen_linked: set[str] = set()

        salary_override = self._employer_salary_override(
            request.user_id, profile.home_currency, request.request_date
        )

        user_events = self.ds.events_by_user.get(request.user_id, [])
        for e in user_events:
            if e.direction in config.NON_CASH_DIRECTIONS:
                continue  # unrealized / non-cash investment value never enters cash flow
            if e.status in config.CANCELLED_STATUSES:
                continue
            eff_date = e.settlement_date or e.event_date
            if eff_date < request.request_date or eff_date > horizon_end:
                # Past settled events are already reflected in current_balance;
                # events beyond the horizon are outside the required forecast.
                continue
            if e.status == "settled":
                # A "settled" row landing inside the forward window is
                # unusual (data already reflects it in the balance); skip to
                # avoid double counting against current_available_balance.
                continue

            # Message-based cancellation/pending override for events tied 1:1
            # to a message (explicit amendment beats the raw row).
            sigs = self._message_signals_for_event(request.user_id, e.event_id)
            if any(s.intent == "cancelled" for s in sigs):
                notes.append(f"Excluded {e.event_id} ({e.category}): message indicates cancellation.")
                continue
            if any(s.intent == "pending" for s in sigs) and e.direction == "credit":
                notes.append(f"Excluded pending credit {e.event_id} ({e.category}): not yet confirmed per message.")
                continue

            # Deduplicate linked lifecycle events: keep only the latest row
            # in a linked chain that falls in the window.
            if e.linked_event_id and e.linked_event_id in seen_linked:
                continue
            if e.linked_event_id:
                seen_linked.add(e.linked_event_id)
            seen_linked.add(e.event_id)

            amount = e.amount
            if amount is None:
                amount = self._resolve_blank_amount(e)
                if amount is None:
                    notes.append(f"Could not resolve blank amount for {e.event_id}; excluded (no fabrication).")
                    continue
                notes.append(f"Resolved blank amount for {e.event_id} from linked image: {amount} {e.currency}.")

            # Income handling: only settled or confirmed-salary credits count.
            if e.direction == "credit":
                if e.status in ("pending", "scheduled") and e.category != "salary":
                    # Bonuses/commissions/refunds/windfalls/investment gains:
                    # do not count until settled.
                    continue
                if e.category == "salary" and salary_override is not None:
                    override_amt, override_cur = salary_override
                    amount = override_amt
                    notes.append(
                        f"Applied employer message salary override for {e.event_id}: {override_amt} {override_cur}."
                    )
                    e = e  # keep currency as override currency (== home currency by construction)
                    currency = override_cur
                else:
                    currency = e.currency
            else:
                currency = e.currency

            home_amount = self.fx.convert(amount, currency, profile.home_currency, eff_date)
            protected, reducible, stoppable = self._classify(e, profile)
            cash_events.append(
                CashEvent(
                    event_id=e.event_id,
                    category=e.category,
                    direction=e.direction,
                    amount=home_amount,
                    on_date=eff_date,
                    flexibility=e.flexibility,
                    protected=protected,
                    reducible=reducible,
                    stoppable=stoppable,
                    minimum_allowed_amount=e.minimum_allowed_amount,
                    description=e.description,
                )
            )

        # Recurrence projection: extend flexible/fixed recurring *expense*
        # categories beyond their last known explicit row, only when history
        # supports it, and only up to the 90-day horizon.
        recurring = self._detect_recurring_categories(request.user_id, request.request_date)
        already_covered_dates: dict[str, list[date]] = {}
        for ce in cash_events:
            already_covered_dates.setdefault(ce.category, []).append(ce.on_date)

        for cat, info in recurring.items():
            is_income = cat == "salary"
            monthly = 25 <= info["interval_days"] <= 35
            next_date = _advance(info["last_date"], info["interval_days"], monthly)
            covered = sorted(already_covered_dates.get(cat, []))
            guard = 0
            while next_date <= horizon_end and guard < 12:
                guard += 1
                if any(abs((next_date - c).days) <= 5 for c in covered):
                    next_date = _advance(next_date, info["interval_days"], monthly)
                    continue
                if next_date >= request.request_date:
                    protected = cat in profile.expense_categories_to_protect
                    reducible = (
                        not is_income
                        and cat in profile.expense_categories_user_is_willing_to_reduce
                        and info["flexibility"] in config.FLEXIBLE_REDUCIBLE
                    )
                    stoppable = (
                        not is_income
                        and cat in profile.expense_categories_user_is_willing_to_stop
                        and info["flexibility"] in config.FLEXIBLE_STOPPABLE
                    )
                    home_amount = self.fx.convert(
                        info["last_amount"], info["last_currency"], profile.home_currency, next_date
                    )
                    cash_events.append(
                        CashEvent(
                            event_id=f"projected_{cat}_{next_date.isoformat()}",
                            category=cat,
                            direction="credit" if is_income else "debit",
                            amount=home_amount,
                            on_date=next_date,
                            flexibility=info["flexibility"],
                            protected=protected if not is_income else True,
                            reducible=reducible,
                            stoppable=stoppable,
                            minimum_allowed_amount=None,
                            is_projected=True,
                            note=f"Projected recurring {cat} at ~{info['interval_days']}d cadence from history.",
                            description=info.get("description", "") or cat.replace("_", " "),
                        )
                    )
                next_date = _advance(next_date, info["interval_days"], monthly)

        cash_events.sort(key=lambda c: (c.on_date, c.event_id))

        options = self.ds.payment_options_by_request.get(request.request_id, [])

        return FinancialState(
            user_id=request.user_id,
            request_id=request.request_id,
            request_date=request.request_date,
            requested_amount=request.requested_amount,
            home_currency=profile.home_currency,
            current_balance=profile.current_available_balance,
            minimum_balance=profile.minimum_balance_to_keep,
            desired_completion_date=request.desired_completion_date,
            priorities=profile.financial_priorities,
            payment_preferences=profile.payment_methods_user_will_consider,
            max_installment_months=profile.max_installment_months,
            forecast_horizon_end=horizon_end,
            cash_events=cash_events,
            payment_options=options,
            evidence_notes=notes,
        )
